server.port=8080
spring.data.mongodb.uri=mongodb+srv://db:1234@cluster0.qe5skxx.mongodb.net/Smart_Campus_DB?retryWrites=true&w=majority
spring.mongodb.uri=mongodb+srv://db:1234@cluster0.qe5skxx.mongodb.net/Smart_Campus_DB?retryWrites=true&w=majority
