server.port=8080
spring.data.mongodb.uri=mongodb+srv://db:1234@cluster0.qe5skxx.mongodb.net/Smart_Campus_DB?retryWrites=true&w=majority
spring.mongodb.uri=mongodb+srv://db:1234@cluster0.qe5skxx.mongodb.net/Smart_Campus_DB?retryWrites=true&w=majority
# JWT
SMARTCAMPUS_JWT_SECRET=205c76fafd3decea9f35dbee99f4d52cf4cb67663e0de83a590addd3b896cb45
SMARTCAMPUS_JWT_EXP_SECONDS=86400
